# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Coverage
on: push
jobs:
  coverage:
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2  # https://github.com/actions/checkout
    - uses: actions/setup-python@v1  # https://github.com/actions/setup-python
      with:
        python-version: '3.9'
        architecture: x64
    - run: pip install nox==2022.11.21
    - run: pip install poetry==1.3.2
    - run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
    - run: nox -s tests coverage -p 3.9
