name: TestPyPI
on:
  push:
    branches:
      - master
jobs:
  test_pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.9'
        architecture: x64
    - run: pip install poetry==1.3.2
    # bump version and add .dev.<timestamp> suffix
    - run: >-
        poetry version patch &&
        version=$(poetry version | awk '{print $2}') &&
        poetry version $version.dev.$(date +%s)
    - run: poetry build
    # https://github.com/pypa/gh-action-pypi-publish
    - uses: pypa/gh-action-pypi-publish@release/v1.6
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_TOKEN }}
        # https://packaging.python.org/en/latest/guides/migrating-to-pypi-org/#using-testpypi
        repository_url: https://test.pypi.org/legacy/
