# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Tests
on: push
jobs:
  tests:
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.8']
    name: Python ${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v2  # https://github.com/actions/checkout
    - uses: actions/setup-python@v1  # https://github.com/actions/setup-python
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - run: pip install nox==2022.11.21
    - run: pip install poetry==1.3.2
    - run: nox --python ${{ matrix.python-version }}
